package com.basic.router.routes;

import com.basic.router.facade.template.IRouteGroup;
import com.basic.router.facade.template.IRouteRoot;

import java.util.Map;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.
 */
public class XRouter$$Root$$app implements IRouteRoot {
  @Override
  public void loadInto(Map<String, Class<? extends IRouteGroup>> routeGroups) {
    routeGroups.put("xpage", XRouter$$Group$$xpage.class);
  }
}
