package com.basic.router.routes;

import com.basic.router.facade.template.IProviderGroup;
import com.basic.router.model.RouteInfo;

import java.util.Map;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.
 */
public class XRouter$$Providers$$app implements IProviderGroup {
  @Override
  public void loadInto(Map<String, RouteInfo> providers) {
  }
}
