package com.basic.router.routes;

import com.basic.router.enums.RouteType;
import com.basic.router.facade.template.IRouteGroup;
import com.basic.router.model.RouteInfo;
import com.basic.code.base.XPageTransferActivity;

import java.util.Map;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.
 */
public class XRouter$$Group$$xpage implements IRouteGroup {
  @Override
  public void loadInto(Map<String, RouteInfo> routeInfos) {
    routeInfos.put("/xpage/transfer", RouteInfo.build(RouteType.ACTIVITY, XPageTransferActivity.class, "/xpage/transfer", "xpage", new java.util.HashMap<String, Integer>(){{put("pageName", 8); }}, -1, -2147483648));
  }
}
